    <?php 
    return [
     'Js1' =>  'js/jquery.min.js',
     'Js2' =>  'js/bootstrap.min.js',
     'Js3' =>  'js/slick.min.js',
     'Js4' =>  'js/nouislider.min.js',
     'Js5' =>  'js/jquery.zoom.min.js',
     'Js6' =>  'js/main.js',
     'searchbar' =>  'js/searchbar.js',

//Admin Page Js files
    'AJs1' =>   'asset/js/excanvas.min.js',
    'AJs2' =>   'asset/js/jquery.min.js',
    'AJs3' =>   'asset/js/jquery.ui.custom.js',
    'AJs4' =>   'asset/js/bootstrap.min.js',
    'AJs5' =>   'asset/js/jquery.flot.min.js', 
    'AJs6' =>   'asset/js/jquery.flot.resize.min.js', 
    'AJs7' =>   'asset/js/jquery.peity.min.js',
    'AJs8' =>   'asset/js/fullcalendar.min.js', 
    'AJs9' =>   'asset/js/matrix.js', 
    'AJs10' =>   'asset/js/matrix.dashboard.js', 
    'AJs11' =>   'asset/js/jquery.gritter.min.js', 
    'AJs12' =>   'asset/js/matrix.interface.js', 
    'AJs13' =>   'asset/js/matrix.chat.js', 
    'AJs14' =>   'asset/js/jquery.validate.js', 
    'AJs15' =>   'asset/js/matrix.form_validation.js', 
    'AJs16' =>   'asset/js/jquery.wizard.js', 
    'AJs17' =>   'asset/js/jquery.uniform.js', 
    'AJs18' =>   'asset/js/select2.min.js', 
    'AJs19' =>   'asset/js/matrix.popover.js', 
    'AJs20' =>   'asset/js/jquery.dataTables.min.js', 
    'AJs21' =>   'asset/js/matrix.tables.js', 
    'AJs22' =>   'asset/matrix.login.js', 
    ]
    ?>